changelog:
  name-template: "v$NEXT_MINOR_VERSION 🦄"
  tag-template: "v$NEXT_MINOR_VERSION"
  categories:
    - title: 🚨 What's new?
    - title: 🏕 Features
      labels:
        - feat
        - update
    - title: 🐛 Bug Fixes
      labels:
        - feat
        - update
    - title: 🦄 ETC
      labels:
        - "*"
