changelog:
  categories:
    - title: 🦄 Features
      labels:
        - Feat
        - Update
    - title: 🐛 Bug Fixes
      labels:
        - Fix
    - title: 🦄 ETC
      labels:
        - "*"
      exclude:
        labels:
        - Feat
        - Update
        - Fix
